# Generated by Django 4.2.29 on 2026-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Название (РУ)'),
        ),
    ]
